In [1]:
import pandas as pd
import numpy as np
import string
import datetime as dt
import math

In [2]:
pd.__version__

'1.1.0'

# 2017-2018 NBA SEASON

In [3]:
df = pd.read_csv("2017-18/raw_scores.csv")

In [4]:
df.columns

Index(['GAME_DATE_EST', 'GAME_SEQUENCE', 'GAME_ID', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'TEAM_CITY_NAME', 'TEAM_WINS_LOSSES', 'PTS_QTR1',
       'PTS_QTR2', 'PTS_QTR3', 'PTS_QTR4', 'PTS_OT1', 'PTS_OT2', 'PTS_OT3',
       'PTS_OT4', 'PTS_OT5', 'PTS_OT6', 'PTS_OT7', 'PTS_OT8', 'PTS_OT9',
       'PTS_OT10', 'PTS', 'FG_PCT', 'FT_PCT', 'FG3_PCT', 'AST', 'REB', 'TOV'],
      dtype='object')

In [7]:
df.PTS_OT4.unique()

array([0], dtype=int64)

In [8]:
df.PTS_OT5.unique()

array([0], dtype=int64)

In [9]:
df.PTS_OT6.unique()

array([0], dtype=int64)

In [10]:
df.PTS_OT7.unique()

array([0], dtype=int64)

In [11]:
df.PTS_OT8.unique()

array([0], dtype=int64)

In [12]:
df.PTS_OT9.unique()

array([0], dtype=int64)

In [6]:
df = df.drop(["PTS_OT4", "PTS_OT5", "PTS_OT6", "PTS_OT7", "PTS_OT8", "PTS_OT9"], axis=1)
df.head()

,GAME_DATE_EST,GAME_SEQUENCE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY_NAME,TEAM_WINS_LOSSES,PTS_QTR1,PTS_QTR2,PTS_QTR3,...,PTS_OT2,PTS_OT3,PTS_OT10,PTS,FG_PCT,FT_PCT,FG3_PCT,AST,REB,TOV
0,2017-10-17,1,21700001,1610612738,BOS,Boston,0-1,19,19,33,...,0,0,0,99,0.409,0.760,0.250,24,46,10
1,2017-10-17,1,21700001,1610612739,CLE,Cleveland,1-0,29,25,18,...,0,0,0,102,0.458,0.840,0.227,19,50,17
2,2017-10-17,2,21700002,1610612745,HOU,Houston,1-0,34,28,26,...,0,0,0,122,0.485,0.684,0.366,28,43,12
3,2017-10-17,2,21700002,1610612744,GSW,Golden State,0-1,35,36,30,...,0,0,0,121,0.538,0.905,0.533,34,41,17
4,2017-10-18,1,21700003,1610612766,CHA,Charlotte,0-1,27,18,25,...,0,0,0,90,0.397,0.793,0.300,16,47,17

In [7]:
df = df.drop(["PTS_OT10"], axis=1)

In [8]:
df.columns

Index(['GAME_DATE_EST', 'GAME_SEQUENCE', 'GAME_ID', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'TEAM_CITY_NAME', 'TEAM_WINS_LOSSES', 'PTS_QTR1',
       'PTS_QTR2', 'PTS_QTR3', 'PTS_QTR4', 'PTS_OT1', 'PTS_OT2', 'PTS_OT3',
       'PTS', 'FG_PCT', 'FT_PCT', 'FG3_PCT', 'AST', 'REB', 'TOV'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2462 entries, 0 to 2461
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   GAME_DATE_EST      2462 non-null   object
 1   GAME_SEQUENCE      2462 non-null   int64
 2   GAME_ID            2462 non-null   int64
 3   TEAM_ID            2462 non-null   int64
 4   TEAM_ABBREVIATION  2462 non-null   object
 5   TEAM_CITY_NAME     2462 non-null   object
 6   TEAM_WINS_LOSSES   2462 non-null   object
 7   PTS_QTR1           2462 non-null   int64
 8   PTS_QTR2           2462 non-null   int64
 9   PTS_QTR3           2462 non-null   int64
 10  PTS_QTR4           2462 non-null   int64
 11  PTS_OT1            2462 non-null   int64
 12  PTS_OT2            2462 non-null   int64
 13  PTS_OT3            2462 non-null   int64
 14  PTS                2462 non-null   int64
 15  FG_PCT             2462 non-null   float64
 16  FT_PCT             2462 non-null   float64
 17  FG3_PCT            2462 non-null   float64
 18  AST                2462 non-null   int64
 19  REB                2462 non-null   int64
 20  TOV                2462 non-null   int64
dtypes: float64(3), int64(14), object(4)
memory usage: 423.2+ KB

In [10]:
df.head()

,GAME_DATE_EST,GAME_SEQUENCE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY_NAME,TEAM_WINS_LOSSES,PTS_QTR1,PTS_QTR2,PTS_QTR3,...,PTS_OT1,PTS_OT2,PTS_OT3,PTS,FG_PCT,FT_PCT,FG3_PCT,AST,REB,TOV
0,2017-10-17,1,21700001,1610612738,BOS,Boston,0-1,19,19,33,...,0,0,0,99,0.409,0.760,0.250,24,46,10
1,2017-10-17,1,21700001,1610612739,CLE,Cleveland,1-0,29,25,18,...,0,0,0,102,0.458,0.840,0.227,19,50,17
2,2017-10-17,2,21700002,1610612745,HOU,Houston,1-0,34,28,26,...,0,0,0,122,0.485,0.684,0.366,28,43,12
3,2017-10-17,2,21700002,1610612744,GSW,Golden State,0-1,35,36,30,...,0,0,0,121,0.538,0.905,0.533,34,41,17
4,2017-10-18,1,21700003,1610612766,CHA,Charlotte,0-1,27,18,25,...,0,0,0,90,0.397,0.793,0.300,16,47,17

In [11]:
vegas_df = pd.read_csv("2017-18/vegas.csv", parse_dates=[0])

In [12]:
vegas_df

,Date,Location,Team,OppTeam,TeamId,GameId,PercentBet_ML,Open_Line_ML,Pinnacle_ML,5dimes_ML,...,Average_Line_OU,Average_Odds_OU,Best_Line_OU,Worst_Line_OU,Best_Odds_OU,Worst_Odds_OU,Pts,Spread,Result,Total
0,2017-10-17,away,Boston,Cleveland,1610612738,21700001,50.4,150.0,166,170,...,216.17,-106.83,216.5,216.0,-101.0,-110,99.0,-3.0,L,201.0
1,2017-10-17,home,Cleveland,Boston,1610612739,21700001,49.6,-170.0,-185,-185,...,216.17,-108.17,216.5,216.0,-105.0,-110,102.0,3.0,W,201.0
2,2017-10-17,away,Houston,Golden State,1610612745,21700002,52.7,405.0,377,420,...,231.75,-109.67,235.0,230.5,-103.0,-115,122.0,1.0,W,243.0
3,2017-10-17,home,Golden State,Houston,1610612744,21700002,47.3,-500.0,-440,-475,...,231.75,-105.33,235.0,230.5,-100.0,-110,121.0,-1.0,L,243.0
4,2017-10-18,away,Charlotte,Detroit,1610612766,21700003,51.3,130.0,127,130,...,202.17,-107.83,203.0,202.0,-102.0,-115,90.0,-12.0,L,192.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,2018-04-11,home,L.A. Clippers,L.A. Lakers,1610612746,21701228,52.2,-145.0,-130,-133,...,215.08,-108.00,217.0,214.5,-103.0,-115,100.0,-15.0,L,215.0
2456,2018-04-11,away,Utah,Portland,1610612762,21701229,58.2,140.0,118,115,...,202.42,-109.33,203.0,202.0,-105.0,-116,93.0,-9.0,L,195.0
2457,2018-04-11,home,Portland,Utah,1610612757,21701229,41.8,-160.0,-130,-125,...,202.42,-107.50,203.0,202.0,-105.0,-110,102.0,9.0,W,195.0
2458,2018-04-11,away,Houston,Sacramento,1610612745,21701230,46.9,-155.0,118,123,...,201.67,-107.50,204.5,201.0,-105.0,-110,83.0,-13.0,L,179.0
2459,2018-04-11,home,Sacramento,Houston,1610612758,21701230,53.1,135.0,-130,-133,...,201.67,-107.50,204.5,201.0,-100.0,-115,96.0,13.0,W,179.0

In [13]:
merged_df = vegas_df.merge(df, left_on=["GameId", "TeamId"], right_on=["GAME_ID", "TEAM_ID"])

In [14]:
merged_df.columns

Index(['Date', 'Location', 'Team', 'OppTeam', 'TeamId', 'GameId',
       'PercentBet_ML', 'Open_Line_ML', 'Pinnacle_ML', '5dimes_ML',
       'Heritage_ML', 'Bovada_ML', 'Betonline_ML', 'Average_Line_ML',
       'Best_Line_ML', 'Worst_Line_ML', 'PercentBet_Spread',
       'Open_Line_Spread', 'Open_Odds_Spread', 'Pinnacle_Line_Spread',
       'Pinnacle_Odds_Spread', '5dimes_Line_Spread', '5dimes_Odds_Spread',
       'Heritage_Line_Spread', 'Heritage_Odds_Spread', 'Bovada_Line_Spread',
       'Bovada_Odds_Spread', 'Betonline_Line_Spread', 'Betonline_Odds_Spread',
       'Average_Line_Spread', 'Average_Odds_Spread', 'Best_Line_Spread',
       'Worst_Line_Spread', 'Best_Odds_Spread', 'Worst_Odds_Spread',
       'PercentBet_OU', 'Open_Line_OU', 'Open_Odds_OU', 'Pinnacle_Line_OU',
       'Pinnacle_Odds_OU', '5dimes_Line_OU', '5dimes_Odds_OU',
       'Heritage_Line_OU', 'Heritage_Odds_OU', 'Bovada_Line_OU',
       'Bovada_Odds_OU', 'Betonline_Line_OU', 'Betonline_Odds_OU',
       'Average_Line_OU', 'Average_Odds_OU', 'Best_Line_OU', 'Worst_Line_OU',
       'Best_Odds_OU', 'Worst_Odds_OU', 'Pts', 'Spread', 'Result', 'Total',
       'GAME_DATE_EST', 'GAME_SEQUENCE', 'GAME_ID', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'TEAM_CITY_NAME', 'TEAM_WINS_LOSSES', 'PTS_QTR1',
       'PTS_QTR2', 'PTS_QTR3', 'PTS_QTR4', 'PTS_OT1', 'PTS_OT2', 'PTS_OT3',
       'PTS', 'FG_PCT', 'FT_PCT', 'FG3_PCT', 'AST', 'REB', 'TOV'],
      dtype='object')

In [15]:
merged_df.groupby('Team').mean()

,TeamId,GameId,PercentBet_ML,Open_Line_ML,Pinnacle_ML,5dimes_ML,Heritage_ML,Bovada_ML,Betonline_ML,Average_Line_ML,...,PTS_OT1,PTS_OT2,PTS_OT3,PTS,FG_PCT,FT_PCT,FG3_PCT,AST,REB,TOV
Team,,,,,,,,,,,,,,,,,,,,,
Atlanta,1.610613e+09,2.170061e+07,47.162195,247.524390,253.548780,266.621951,253.375000,232.073171,247.829268,250.163415,...,0.121951,0.000000,0.000000,103.353659,0.447720,0.787098,0.363463,23.731707,41.902439,15.000000
Boston,1.610613e+09,2.170060e+07,56.830488,-162.073171,-126.390244,-129.024390,-136.358025,-156.158537,-140.219512,-138.571951,...,0.536585,0.109756,0.000000,104.012195,0.451280,0.771622,0.381280,22.463415,44.451220,13.317073
Brooklyn,1.610613e+09,2.170061e+07,47.236585,190.333333,207.609756,201.524390,199.512195,165.061728,182.333333,197.252439,...,0.585366,0.048780,0.000000,106.597561,0.442146,0.779146,0.355890,23.670732,44.439024,14.231707
Charlotte,1.610613e+09,2.170062e+07,43.520732,-32.987805,-57.170732,-72.707317,-63.292683,-58.719512,-61.085366,-62.595122,...,0.560976,0.000000,0.000000,108.219512,0.450598,0.747366,0.362878,21.585366,45.463415,12.329268
Chicago,1.610613e+09,2.170062e+07,50.650000,243.487805,259.658537,246.170732,251.125000,239.938272,251.292683,250.253659,...,0.524390,0.195122,0.000000,102.926829,0.435841,0.757037,0.353512,23.451220,44.670732,13.292683
Cleveland,1.610613e+09,2.170062e+07,56.537805,-293.914634,-273.390244,-232.560976,-291.585366,-331.463415,-288.268293,-283.453659,...,0.292683,0.000000,0.000000,110.865854,0.477232,0.778085,0.372366,23.365854,42.134146,13.304878
Dallas,1.610613e+09,2.170061e+07,45.351220,166.629630,171.524390,192.256098,175.426829,164.085366,159.777778,174.076220,...,0.439024,0.000000,0.000000,102.317073,0.445512,0.763183,0.360890,22.658537,41.256098,11.756098
Denver,1.610613e+09,2.170062e+07,45.173171,-94.000000,-106.341463,-86.951220,-122.682927,-117.621951,-113.280488,-109.375610,...,0.890244,0.121951,0.000000,110.000000,0.470341,0.770963,0.367207,25.109756,44.512195,14.329268
Detroit,1.610613e+09,2.170062e+07,48.780488,-20.475610,-19.658537,-7.573171,-30.426829,-37.134146,-19.695122,-22.897561,...,0.402439,0.000000,0.000000,103.768293,0.450159,0.741378,0.372280,22.780488,43.731707,12.756098
Golden State,1.610613e+09,2.170061e+07,49.039024,-535.189873,-545.853659,-565.914634,-596.666667,-636.219512,-545.493671,-587.151220,...,0.390244,0.000000,0.000000,113.463415,0.503366,0.813927,0.388671,29.292683,43.512195,14.987805
Houston,1.610613e+09,2.170062e+07,51.532927,-518.804878,-545.951220,-536.292683,-562.743902,-504.687500,-541.500000,-550.126220,...,0.280488,0.182927,0.000000,112.353659,0.460305,0.780232,0.363829,21.548780,43.463415,13.170732
Indiana,1.610613e+09,2.170060e+07,50.865854,-6.987805,0.914634,16.219512,-7.439024,-11.951220,-5.195122,-1.490244,...,0.500000,0.000000,0.000000,105.560976,0.473073,0.781451,0.365768,22.182927,42.341463,12.768293
L.A. Clippers,1.610613e+09,2.170063e+07,48.798780,-2.073171,0.743902,-34.243902,-3.231707,-15.548780,-0.658537,-10.587805,...,0.097561,0.000000,0.000000,108.987805,0.472963,0.739317,0.351159,22.341463,43.890244,14.073171
L.A. Lakers,1.610613e+09,2.170063e+07,53.235366,144.890244,146.243902,154.329268,148.475610,129.756098,140.878049,143.936585,...,1.134146,0.109756,0.000000,108.073171,0.460890,0.718451,0.339976,23.768293,46.378049,15.317073
Memphis,1.610613e+09,2.170062e+07,46.215854,206.530864,236.548780,226.439024,228.475610,197.469136,221.925926,228.434756,...,0.109756,0.000000,0.000000,99.329268,0.444256,0.782098,0.350988,21.548780,40.524390,14.414634
Miami,1.610613e+09,2.170062e+07,47.501220,-59.414634,-51.024390,-49.634146,-62.682927,-71.049383,-64.207317,-59.419512,...,1.170732,0.219512,0.000000,103.414634,0.456024,0.755768,0.357976,22.707317,43.463415,13.634146
Milwaukee,1.610613e+09,2.170063e+07,51.786585,-83.902439,-90.292683,-75.243902,-96.585366,-102.500000,-98.926829,-92.709756,...,0.804878,0.000000,0.000000,106.475610,0.478927,0.784073,0.356268,23.231707,39.841463,13.146341
Minnesota,1.610613e+09,2.170060e+07,51.212195,-194.048780,-185.841463,-171.707317,-201.036585,-205.792683,-196.170732,-192.109756,...,0.743902,0.000000,0.000000,109.512195,0.477512,0.802329,0.358000,22.695122,41.963415,11.743902
New Orleans,1.610613e+09,2.170062e+07,49.175610,-63.536585,-63.182927,-63.121951,-74.634146,-81.524390,-75.719512,-71.636585,...,1.146341,0.292683,0.000000,111.719512,0.484329,0.774354,0.359439,26.768293,44.341463,14.414634
New York,1.610613e+09,2.170061e+07,50.803659,195.682927,215.743902,235.134146,208.414634,189.878049,201.975610,210.229268,...,0.573171,0.085366,0.000000,104.463415,0.464744,0.786817,0.352585,23.317073,44.036585,14.195122
Oklahoma City,1.610613e+09,2.170061e+07,55.209756,-256.365854,-267.695122,-245.975610,-283.658537,-265.617284,-274.804878,-274.076220,...,0.487805,0.109756,0.097561,107.853659,0.453220,0.714646,0.352146,21.341463,45.060976,13.439024
Orlando,1.610613e+09,2.170061e+07,50.270732,182.695122,193.487805,188.341463,189.695122,177.987805,190.963415,188.095122,...,0.304878,0.000000,0.000000,103.402439,0.452963,0.761866,0.348012,23.426829,41.634146,13.939024
Philadelphia,1.610613e+09,2.170063e+07,48.778049,-120.975309,-140.402439,-151.134146,-156.585366,-171.707317,-147.938272,-156.055488,...,0.317073,0.109756,0.073171,109.804878,0.472463,0.759268,0.366890,27.085366,47.426829,15.865854
Phoenix,1.610613e+09,2.170060e+07,49.524390,334.137500,369.000000,377.402439,377.256098,321.111111,348.887500,364.776829,...,0.024390,0.000000,0.000000,103.926829,0.443305,0.737585,0.335378,21.256098,44.121951,15.060976
Portland,1.610613e+09,2.170062e+07,53.963415,-85.259259,-101.621951,-107.439024,-119.817073,-131.707317,-91.962963,-114.974390,...,0.402439,0.000000,0.000000,105.621951,0.453500,0.805256,0.367341,19.500000,45.463415,13.012195
Sacramento,1.610613e+09,2.170062e+07,50.342683,277.426829,298.939024,315.890244,294.024390,272.256098,287.939024,293.809756,...,0.512195,0.000000,0.000000,98.829268,0.450768,0.740573,0.376915,21.560976,40.914634,13.207317
San Antonio,1.610613e+09,2.170061e+07,52.496341,-175.731707,-158.804878,-191.963415,-179.756098,-201.463415,-166.780488,-179.753659,...,0.170732,0.000000,0.000000,102.731707,0.457756,0.778098,0.352256,22.780488,44.219512,12.682927
Toronto,1.610613e+09,2.170063e+07,51.528049,-288.317073,-290.134146,-283.939024,-315.365854,-329.939024,-300.621951,-304.000000,...,0.731707,0.000000,0.000000,111.658537,0.472683,0.788061,0.357232,24.329268,43.987805,12.743902
Utah,1.610613e+09,2.170061e+07,48.389024,-148.121951,-150.597561,-127.634146,-157.134146,-167.195122,-160.878049,-152.687805,...,0.402439,0.000000,0.000000,104.146341,0.462476,0.783317,0.366537,22.426829,43.256098,14.085366
Washington,1.610613e+09,2.170061e+07,48.087805,-135.121951,-119.036585,-113.719512,-129.207317,-131.829268,-122.768293,-123.312195,...,0.682927,0.121951,0.000000,106.609756,0.467671,0.774695,0.372963,25.182927,43.121951,14.048780

In [16]:
season_df = pd.read_csv("2017-18/17-18-cover.csv")
season_df.loc[13, "Team"] = "Oklahoma City"
season_df.loc[3, "Team"] = "L.A. Clippers"
season_df.loc[27, "Team"] = "L.A. Lakers"

In [17]:
season_df

             Team  Cover %   Win  Loss  Tie
0       Milwaukee     61.3  57.0  36.0  4.0
1          Dallas     56.8  46.0  35.0  1.0
2      Sacramento     56.2  45.0  35.0  2.0
3   L.A. Clippers     55.2  48.0  39.0  1.0
4        Portland     54.2  52.0  44.0  2.0
5         Orlando     54.1  46.0  39.0  2.0
6            Utah     54.1  46.0  39.0  2.0
7     San Antonio     53.4  47.0  41.0  1.0
8           Miami     53.1  43.0  38.0  1.0
9        Brooklyn     52.9  46.0  41.0  0.0
10        Houston     52.2  47.0  43.0  3.0
11        Atlanta     51.2  42.0  40.0  0.0
12         Denver     51.0  49.0  47.0  0.0
13  Oklahoma City     50.6  44.0  43.0  0.0
14   Philadelphia     48.9  46.0  48.0  0.0
15        Detroit     48.8  41.0  43.0  2.0
16      Minnesota     48.8  40.0  42.0  0.0
17      Charlotte     48.8  39.0  41.0  2.0
18        Toronto     48.6  51.0  54.0  1.0
19         Boston     48.3  43.0  46.0  2.0
20        Memphis     48.1  39.0  42.0  1.0
21        Indiana     47.1  40.0  45.0  1.0
22    New Orleans     46.9  38.0  43.0  1.0
23      Cleveland     46.9  38.0  43.0  1.0
24     Washington     46.3  38.0  44.0  0.0
25        Phoenix     43.9  36.0  46.0  0.0
26        Chicago     43.8  35.0  45.0  2.0
27    L.A. Lakers     43.2  35.0  46.0  1.0
28   Golden State     43.1  44.0  58.0  2.0
29       New York     40.5  32.0  47.0  3.0

In [18]:
new_df = merged_df.merge(season_df, on='Team')

In [19]:
total_df = new_df.loc[:, ["Team", "Location", "Win", "Loss", "Tie","Cover %", "PercentBet_Spread", "Average_Line_Spread",
               "Average_Odds_Spread", "PTS", "FG_PCT", "FT_PCT", "FG3_PCT"]]

In [20]:
total_df.groupby('Team').mean().sort_values('PercentBet_Spread', ascending=False)

,Win,Loss,Tie,Cover %,PercentBet_Spread,Average_Line_Spread,Average_Odds_Spread,PTS,FG_PCT,FT_PCT,FG3_PCT
Team,,,,,,,,,,,
Cleveland,38.0,43.0,1.0,46.9,56.035366,-4.414634,-107.873659,110.865854,0.477232,0.778085,0.372366
Boston,43.0,46.0,2.0,48.3,55.576829,-2.640244,-107.499390,104.012195,0.451280,0.771622,0.381280
Golden State,44.0,58.0,2.0,43.1,55.334146,-8.502073,-107.717561,113.463415,0.503366,0.813927,0.388671
Portland,52.0,44.0,2.0,54.2,55.292683,-1.543902,-107.983659,105.621951,0.453500,0.805256,0.367341
San Antonio,47.0,41.0,1.0,53.4,54.345122,-3.060976,-106.947073,102.731707,0.457756,0.778098,0.352256
Oklahoma City,44.0,43.0,0.0,50.6,53.721951,-4.465732,-107.900610,107.853659,0.453220,0.714646,0.352146
Houston,47.0,43.0,3.0,52.2,52.810976,-7.490244,-107.662805,112.353659,0.460305,0.780232,0.363829
Toronto,51.0,54.0,1.0,48.6,52.335366,-5.483537,-107.323293,111.658537,0.472683,0.788061,0.357232
Indiana,40.0,45.0,1.0,47.1,51.691463,0.352439,-107.478171,105.560976,0.473073,0.781451,0.365768
Philadelphia,46.0,48.0,0.0,48.9,51.246341,-2.348537,-107.753659,109.804878,0.472463,0.759268,0.366890
Milwaukee,57.0,36.0,4.0,61.3,50.825610,-1.538415,-107.859268,106.475610,0.478927,0.784073,0.356268
Washington,38.0,44.0,0.0,46.3,50.652439,-2.140488,-107.598049,106.609756,0.467671,0.774695,0.372963
Denver,49.0,47.0,0.0,51.0,50.602439,-1.896707,-107.729756,110.000000,0.470341,0.770963,0.367207
Utah,46.0,39.0,2.0,54.1,50.442683,-1.539756,-108.101463,104.146341,0.462476,0.783317,0.366537
L.A. Lakers,35.0,46.0,1.0,43.2,50.186585,3.509634,-107.442927,108.073171,0.460890,0.718451,0.339976
Detroit,41.0,43.0,2.0,48.8,49.721951,0.072317,-107.441463,103.768293,0.450159,0.741378,0.372280
L.A. Clippers,48.0,39.0,1.0,55.2,49.298780,0.446220,-107.796707,108.987805,0.472963,0.739317,0.351159
Minnesota,40.0,42.0,0.0,48.8,48.875610,-2.772439,-107.601463,109.512195,0.477512,0.802329,0.358000
New Orleans,38.0,43.0,1.0,46.9,48.634146,-0.912195,-107.882073,111.719512,0.484329,0.774354,0.359439
New York,32.0,47.0,3.0,40.5,48.031707,4.510610,-107.743902,104.463415,0.464744,0.786817,0.352585
Charlotte,39.0,41.0,2.0,48.8,47.796341,-0.738902,-107.967195,108.219512,0.450598,0.747366,0.362878
Phoenix,36.0,46.0,0.0,43.9,46.865854,7.356707,-107.408780,103.926829,0.443305,0.737585,0.335378
Dallas,46.0,35.0,1.0,56.8,46.793902,4.140122,-107.648049,102.317073,0.445512,0.763183,0.360890
Sacramento,45.0,35.0,2.0,56.2,46.562195,6.588537,-107.266707,98.829268,0.450768,0.740573,0.376915
Orlando,46.0,39.0,2.0,54.1,46.528049,4.480122,-107.532561,103.402439,0.452963,0.761866,0.348012
Brooklyn,46.0,41.0,0.0,52.9,46.425610,4.537805,-107.556951,106.597561,0.442146,0.779146,0.355890
Chicago,35.0,45.0,2.0,43.8,46.318293,5.864390,-107.642805,102.926829,0.435841,0.757037,0.353512
Miami,43.0,38.0,1.0,53.1,46.071951,-0.543537,-107.638171,103.414634,0.456024,0.755768,0.357976
Memphis,39.0,42.0,1.0,48.1,45.642683,4.459756,-107.262195,99.329268,0.444256,0.782098,0.350988
Atlanta,42.0,40.0,0.0,51.2,45.332927,5.693293,-107.608171,103.353659,0.447720,0.787098,0.363463

In [21]:
series_diff = (total_df.groupby('Team').mean()["Cover %"] - total_df.groupby('Team').mean()["PercentBet_Spread"])

In [22]:
grouped_df = total_df.groupby('Team').mean().sort_values('Cover %', ascending=False)

In [23]:
grouped_df=grouped_df.reset_index()

In [24]:
new_grouped_df = grouped_df.merge((series_diff.reset_index()), on="Team")

In [25]:
new_grouped_df.rename(columns={0: "Cover% - PercentBetSpread"}, inplace=True)

In [26]:
new_grouped_df

,Team,Win,Loss,Tie,Cover %,PercentBet_Spread,Average_Line_Spread,Average_Odds_Spread,PTS,FG_PCT,FT_PCT,FG3_PCT,Cover% - PercentBetSpread
0,Milwaukee,57.0,36.0,4.0,61.3,50.825610,-1.538415,-107.859268,106.475610,0.478927,0.784073,0.356268,10.474390
1,Dallas,46.0,35.0,1.0,56.8,46.793902,4.140122,-107.648049,102.317073,0.445512,0.763183,0.360890,10.006098
2,Sacramento,45.0,35.0,2.0,56.2,46.562195,6.588537,-107.266707,98.829268,0.450768,0.740573,0.376915,9.637805
3,L.A. Clippers,48.0,39.0,1.0,55.2,49.298780,0.446220,-107.796707,108.987805,0.472963,0.739317,0.351159,5.901220
4,Portland,52.0,44.0,2.0,54.2,55.292683,-1.543902,-107.983659,105.621951,0.453500,0.805256,0.367341,-1.092683
5,Utah,46.0,39.0,2.0,54.1,50.442683,-1.539756,-108.101463,104.146341,0.462476,0.783317,0.366537,3.657317
6,Orlando,46.0,39.0,2.0,54.1,46.528049,4.480122,-107.532561,103.402439,0.452963,0.761866,0.348012,7.571951
7,San Antonio,47.0,41.0,1.0,53.4,54.345122,-3.060976,-106.947073,102.731707,0.457756,0.778098,0.352256,-0.945122
8,Miami,43.0,38.0,1.0,53.1,46.071951,-0.543537,-107.638171,103.414634,0.456024,0.755768,0.357976,7.028049
9,Brooklyn,46.0,41.0,0.0,52.9,46.425610,4.537805,-107.556951,106.597561,0.442146,0.779146,0.355890,6.474390
10,Houston,47.0,43.0,3.0,52.2,52.810976,-7.490244,-107.662805,112.353659,0.460305,0.780232,0.363829,-0.610976
11,Atlanta,42.0,40.0,0.0,51.2,45.332927,5.693293,-107.608171,103.353659,0.447720,0.787098,0.363463,5.867073
12,Denver,49.0,47.0,0.0,51.0,50.602439,-1.896707,-107.729756,110.000000,0.470341,0.770963,0.367207,0.397561
13,Oklahoma City,44.0,43.0,0.0,50.6,53.721951,-4.465732,-107.900610,107.853659,0.453220,0.714646,0.352146,-3.121951
14,Philadelphia,46.0,48.0,0.0,48.9,51.246341,-2.348537,-107.753659,109.804878,0.472463,0.759268,0.366890,-2.346341
15,Detroit,41.0,43.0,2.0,48.8,49.721951,0.072317,-107.441463,103.768293,0.450159,0.741378,0.372280,-0.921951
16,Charlotte,39.0,41.0,2.0,48.8,47.796341,-0.738902,-107.967195,108.219512,0.450598,0.747366,0.362878,1.003659
17,Minnesota,40.0,42.0,0.0,48.8,48.875610,-2.772439,-107.601463,109.512195,0.477512,0.802329,0.358000,-0.075610
18,Toronto,51.0,54.0,1.0,48.6,52.335366,-5.483537,-107.323293,111.658537,0.472683,0.788061,0.357232,-3.735366
19,Boston,43.0,46.0,2.0,48.3,55.576829,-2.640244,-107.499390,104.012195,0.451280,0.771622,0.381280,-7.276829
20,Memphis,39.0,42.0,1.0,48.1,45.642683,4.459756,-107.262195,99.329268,0.444256,0.782098,0.350988,2.457317
21,Indiana,40.0,45.0,1.0,47.1,51.691463,0.352439,-107.478171,105.560976,0.473073,0.781451,0.365768,-4.591463
22,Cleveland,38.0,43.0,1.0,46.9,56.035366,-4.414634,-107.873659,110.865854,0.477232,0.778085,0.372366,-9.135366
23,New Orleans,38.0,43.0,1.0,46.9,48.634146,-0.912195,-107.882073,111.719512,0.484329,0.774354,0.359439,-1.734146
24,Washington,38.0,44.0,0.0,46.3,50.652439,-2.140488,-107.598049,106.609756,0.467671,0.774695,0.372963,-4.352439
25,Phoenix,36.0,46.0,0.0,43.9,46.865854,7.356707,-107.408780,103.926829,0.443305,0.737585,0.335378,-2.965854
26,Chicago,35.0,45.0,2.0,43.8,46.318293,5.864390,-107.642805,102.926829,0.435841,0.757037,0.353512,-2.518293
27,L.A. Lakers,35.0,46.0,1.0,43.2,50.186585,3.509634,-107.442927,108.073171,0.460890,0.718451,0.339976,-6.986585
28,Golden State,44.0,58.0,2.0,43.1,55.334146,-8.502073,-107.717561,113.463415,0.503366,0.813927,0.388671,-12.234146
29,New York,32.0,47.0,3.0,40.5,48.031707,4.510610,-107.743902,104.463415,0.464744,0.786817,0.352585,-7.531707